version: '3'

services:
  loadtest:
    environment:
      - REDIS_ADDRESS=redis:6379
      - ENABLE_DISTRIBUTED_CONTROL=true
    build: .
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
