name: Build OTA on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GH_PAT }}

      - name: Clone anki-deps to ~/.anki
        run: |
          git clone https://kercre123:${{ secrets.GH_PAT }}@github.com/kercre123/anki-deps.git ~/.anki


      - name: Set up cache for Docker and build dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache
            /var/lib/docker
            ~/.anki
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Install dependencies
        run: |
          sudo apt-get remove containerd.io
          sudo apt-get update
          sudo apt-get install -y docker.io git-lfs rsync ssh
          sudo systemctl start docker
          sudo gpasswd -a $USER docker
          newgrp docker
          git lfs install

      - name: Build inside Docker
        run: |
          cd $GITHUB_WORKSPACE
          ./wire/build-d.sh

      - name: Get tag version
        id: get_tag
        run: echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build OTA files
        run: |
          tag_version=${{ env.tag_name }}
          cd ota
          ./make.sh $tag_version
        env:
          DOCKER_BUILDKIT: 1

      - name: Rename and organize OTA files
        run: |
          tag_version=${{ env.tag_name }}
          mkdir -p /tmp/ota_artifacts
          for target in dvt3 dev whiskey oskr; do
            find ./out/$tag_version/$target/ -name "*.ota" -exec cp {} /tmp/ota_artifacts/${tag_version}-$target.ota \;
          done

      - name: Upload OTA artifacts to release if tagged
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: /tmp/ota_artifacts
          asset_name: ${{ env.tag_name }}.ota
          label: "OTA files"

      - name: Upload build artifacts
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v3
        with:
          name: OTA-files-${{ env.tag_name }}
          path: /tmp/ota_artifacts
